### ISSUE TITLE
Error: Cannot find module '@millihq/terraform-next-proxy/dist.zip'

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [milliHQ/terraform-aws-next-js#195]
My environments:
- current main branch(a8d121a8a8d128aabc64e963d57c4232f87d7372)

On the example/complete, when I use following settings,
```
  source = "../.."
  debug_use_local_packages = true
```

Below `MODULE_NOT_FOUND` errors occur.
It's strange why it doesn't look for packages in local when `debug_use_local_packages: true` is set.

```
│ Error: failed to execute "node": internal/modules/cjs/loader.js:883
│   throw err;
│   ^
│
│ Error: Cannot find module '@millihq/terraform-next-proxy/dist.zip'
│ Require stack:
│ - /Users/aluc/project/terraform-aws-next-js/[eval]
│     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
│     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
│     at [eval]:3:19
│     at Script.runInThisContext (vm.js:133:18)
│     at Object.runInThisContext (vm.js:310:38)
│     at internal/process/execution.js:77:19
│     at [eval]-wrapper:6:22
│     at evalScript (internal/process/execution.js:76:60)
│     at internal/main/eval_string.js:23:3 {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [ '/Users/aluc/project/terraform-aws-next-js/[eval]' ]
│ }
│
│
│   with module.tf_next.module.proxy.module.proxy_package.data.external.this[0],
│   on .terraform/modules/tf_next.proxy.proxy_package/main.tf line 21, in data "external" "this":
│   21: data "external" "this" {
│
╵
╷
│ Error: failed to execute "node": internal/modules/cjs/loader.js:883
│   throw err;
│   ^
│
│ Error: Cannot find module '@dealmore/terraform-next-deploy-trigger/dist.zip'
│ Require stack:
│ - /Users/aluc/project/terraform-aws-next-js/[eval]
│     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
│     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
│     at [eval]:3:19
│     at Script.runInThisContext (vm.js:133:18)
│     at Object.runInThisContext (vm.js:310:38)
│     at internal/process/execution.js:77:19
│     at [eval]-wrapper:6:22
│     at evalScript (internal/process/execution.js:76:60)
│     at internal/main/eval_string.js:23:3 {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [ '/Users/aluc/project/terraform-aws-next-js/[eval]' ]
│ }
│
│
│   with module.tf_next.module.statics_deploy.module.lambda_content.data.external.this[0],
│   on .terraform/modules/tf_next.statics_deploy.lambda_content/main.tf line 21, in data "external" "this":
│   21: data "external" "this" {
```

I also can not build runtime package due to the error below:

```
$ npm run build

> @dealmore/tf-next-runtime@1.1.0 build
> ./build.sh

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@dealmore/terraform-next-node-bridge/src/bridge.ts'
Require stack:
- /Users/aluc/project/terraform-aws-next-js/packages/runtime/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at [eval]:1:23
    at Script.runInThisContext (vm.js:133:18)
    at Object.runInThisContext (vm.js:310:38)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_string.js:23:3 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/aluc/project/terraform-aws-next-js/packages/runtime/[eval]' ]
}
```

**Comment by ofhouse** [comment]
Yes, the feature lacks some documentation.
In general running `yarn` in the root of the repo and then `yarn build` in each of these packages should work:

- packages/proxy
- packages/deploy-trigger

After that in both packages a `dist.zip` should have been created (e.g `packages/proxy/dist.zip`) which then can be picked up by the `debug_use_local_packages`.

**Comment by ofhouse** [comment]
I created a contributing guide which now covers the usage with `debug_use_local_packages `: https://github.com/milliHQ/terraform-aws-next-js/blob/main/CONTRIBUTING.md#use-local-build-of-the-components

Hope this helps

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
I'll try again as you described.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
As you said, there is no problem if I use `yarn` . However, there is a problem when using `npm`. I'd like to add to the guide a warning about using npm, what do you think?

To test in a clean state, I received a new clone of the repository and tested it.
```
$ git clone git@github.com:milliHQ/terraform-aws-next-js.git test-195-issue
Cloning into 'test-195-issue'...
remote: Enumerating objects: 5757, done.
remote: Counting objects: 100% (1331/1331), done.
remote: Compressing objects: 100% (704/704), done.
remote: Total 5757 (delta 747), reused 1067 (delta 588), pack-reused 4426
Receiving objects: 100% (5757/5757), 4.40 MiB | 4.19 MiB/s, done.
Resolving deltas: 100% (3181/3181), done.
Time: 0h:00m:04s

$ cd test-195-issue
$ node --version
v14.17.6
$ npm --version
6.14.15

$ npm install

> aws-sdk@2.993.0 postinstall /Users/aluc/project/test-195-issue/node_modules/aws-sdk
> node scripts/check-node-version.js

npm notice created a lockfile as package-lock.json. You should commit this file.
added 405 packages from 420 contributors and audited 408 packages in 7.374s
 27 0 info it worked if it ends with ok
 27 1 verbose cli [
 27 1 verbose cli   '/Users/aluc/.nvm/versions/node/v14.17.6/bin/node',
 27 1 verbose cli   '/Users/aluc/.nvm/versions/node/v14.17.6/bin/npm',
 27 1 verbose cli   'run',
 27 1 verbose cli   'build'
 27 1 verbose cli ]
 27 2 info using npm@6.14.15
 27 3 info using node@v14.17.6
 27 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]

27 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Time: 0h:00m:08s
$ cd packages/runtime
$ npm run build

> @millihq/tf-next-runtime@1.0.0-canary.1 build /Users/aluc/project/test-195-issue/packages/runtime
> ./build.sh

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '@millihq/terraform-next-node-bridge/src/bridge.ts'
Require stack:
- /Users/aluc/project/test-195-issue/packages/runtime/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at [eval]:1:23
    at Script.runInThisContext (vm.js:134:12)
    at Object.runInThisContext (vm.js:310:38)
    at internal/process/execution.js:81:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:80:60)
    at internal/main/eval_string.js:27:3 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/aluc/project/test-195-issue/packages/runtime/[eval]' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @millihq/tf-next-runtime@1.0.0-canary.1 build: `./build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @millihq/tf-next-runtime@1.0.0-canary.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aluc/.npm/_logs/2021-09-23T06_07_32_554Z-debug.log
```

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@ofhouse Thanks. **As you said, there is no problem if I use `yarn`.**

However, there is a problem when using `npm`. I'd like to add to the guide a warning about using npm, what do you think?

To test in a clean state, I received a new clone of the repository and tested it.
```
$ git clone git@github.com:milliHQ/terraform-aws-next-js.git test-195-issue
Cloning into 'test-195-issue'...
remote: Enumerating objects: 5757, done.
remote: Counting objects: 100% (1331/1331), done.
remote: Compressing objects: 100% (704/704), done.
remote: Total 5757 (delta 747), reused 1067 (delta 588), pack-reused 4426
Receiving objects: 100% (5757/5757), 4.40 MiB | 4.19 MiB/s, done.
Resolving deltas: 100% (3181/3181), done.
Time: 0h:00m:04s

$ cd test-195-issue
$ node --version
v14.17.6
$ npm --version
6.14.15

$ npm install

> aws-sdk@2.993.0 postinstall /Users/aluc/project/test-195-issue/node_modules/aws-sdk
> node scripts/check-node-version.js

npm notice created a lockfile as package-lock.json. You should commit this file.
added 405 packages from 420 contributors and audited 408 packages in 7.374s
 27 0 info it worked if it ends with ok
 27 1 verbose cli [
 27 1 verbose cli   '/Users/aluc/.nvm/versions/node/v14.17.6/bin/node',
 27 1 verbose cli   '/Users/aluc/.nvm/versions/node/v14.17.6/bin/npm',
 27 1 verbose cli   'run',
 27 1 verbose cli   'build'
 27 1 verbose cli ]
 27 2 info using npm@6.14.15
 27 3 info using node@v14.17.6
 27 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]

27 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Time: 0h:00m:08s
$ cd packages/runtime
$ npm run build

> @millihq/tf-next-runtime@1.0.0-canary.1 build /Users/aluc/project/test-195-issue/packages/runtime
> ./build.sh

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '@millihq/terraform-next-node-bridge/src/bridge.ts'
Require stack:
- /Users/aluc/project/test-195-issue/packages/runtime/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at [eval]:1:23
    at Script.runInThisContext (vm.js:134:12)
    at Object.runInThisContext (vm.js:310:38)
    at internal/process/execution.js:81:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:80:60)
    at internal/main/eval_string.js:27:3 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/aluc/project/test-195-issue/packages/runtime/[eval]' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @millihq/tf-next-runtime@1.0.0-canary.1 build: `./build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @millihq/tf-next-runtime@1.0.0-canary.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aluc/.npm/_logs/2021-09-23T06_07_32_554Z-debug.log
```

**Comment by ofhouse** [comment]
If that helps, sure I am not against adding a notice to [CONTRIBUTING.md](https://github.com/milliHQ/terraform-aws-next-js/blob/main/CONTRIBUTING.md).

Would it work with npm 7.x?
Since support for workspaces was added in [npm 7](https://docs.npmjs.com/cli/v7/using-npm/workspaces), so therefore I am not surprised that much that npm 6 fails installing a monorepo.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@ofhouse I used version 6, I'll check it again in npm 7 version.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
It works well with npm 7.x. Since the CONTRIBUTING.md already guides using yarn, it is better not to add about npm, because there is a lot of work to cover the use of npm. Thanks.
