### ISSUE TITLE
[Question] Nextjs 12 + Framer Motion error

### ISSUE THREAD

**Issue by khuezy** [milliHQ/terraform-aws-next-js#280]
Hi, I'm using the latest nextjs and framer motion library and everything works locally, but once I deploy the app... I see this error:
```
2022-02-07T03:05:58.681Z	1d8dc255-acda-48d4-b792-da424a5402f9	ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/tslib/modules/index.js' imported from /var/task/node_modules/framer-motion/dist/es/render/dom/motion.mjs
Did you mean to import tslib/tslib.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:308:11)
    at moduleResolve (internal/modules/esm/resolve.js:731:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Downgrading to Nextjs 11 works. This is related to the esm changes in 12 but would you know why it's erroring on lambda and not locally?

Thanks!

**Comment by khuezy** [comment]
Oops, there's already an open discussion on this.

**Comment by mohalsherif** [comment]
@khuezy can you please link the open discussion? We had the same problem

**Comment by ofhouse** [comment]
@mohalsherif See this issue: https://github.com/milliHQ/terraform-aws-next-js/issues/275
